// A separate, user-paced viewing room keeps exploration distinct from searching.
const room=element('dialog','discovery-room');room.id='discoveryRoom';room.setAttribute('aria-label','Discover a dance');document.body.append(room);
const archiveControl=element('div','archive-switch');archiveControl.setAttribute('role','group');$('searchForm').after(archiveControl);
let recordingMode=false,deck=[],position=-1,roomFilter='',autoPlay=read('autoplay',false),touchStart=null,activeRecording=null;
const originalFiltered=filtered;
filtered=function(){const grouped=originalFiltered();if(!recordingMode)return grouped;const query=normalize($('search').value).split(' ').filter(Boolean);const list=grouped.flatMap(g=>g.records.filter(v=>(tab!=='learn'||v.type==='teaching')&&(!$('formation').value||v.style===$('formation').value)&&(!$('choreographer').value||v.choreoKey===$('choreographer').value)&&(!$('decade').value||Math.floor(v.year/10)*10===Number($('decade').value))&&query.every(q=>normalize(`${v.he} ${v.en} ${v.rom||''} ${v.choreoHe||''} ${v.choreoEn||''}`).includes(q))).map(v=>({...g,main:v,records:[v]})));const order=$('sort').value;return list.sort((a,b)=>tab==='recent'?recent.indexOf(a.key)-recent.indexOf(b.key):order==='az'?title(a).localeCompare(title(b),lang):order==='new'?(b.main.year||0)-(a.main.year||0):order==='old'?(a.main.year||9999)-(b.main.year||9999):b.main.vn-a.main.vn)};
const originalRender=render;render=function(){originalRender();if(recordingMode){const list=filtered();$('resultCount').textContent=t(`מוצגות ${Math.min(limit,list.length)} מתוך ${list.length} הקלטות`,`Showing ${Math.min(limit,list.length)} of ${list.length} recordings`)}syncEntry();syncFavorites()};
function syncEntry(){document.querySelectorAll('.discover-launch').forEach(b=>b.onclick=startDiscover);archiveControl.setAttribute('aria-label',t('דרך התצוגה','Archive view'));room.setAttribute('aria-label',t('לגלות ריקוד','Discover a dance'));archiveControl.replaceChildren();const segments=element('div','archive-segments'),select=element('select','archive-select');select.setAttribute('aria-label',t('דרך התצוגה','Archive view'));for(const [value,label]of [[false,t('לפי ריקוד','By dance')],[true,t('כל ההקלטות','Every recording')]]){const b=element('button','',label);b.setAttribute('aria-pressed',recordingMode===value);b.onclick=()=>{recordingMode=value;limit=18;render()};segments.append(b);const o=element('option','',label);o.value=String(value);select.append(o)}select.value=String(recordingMode);select.onchange=()=>{recordingMode=select.value==='true';limit=18;render()};archiveControl.append(segments,select)}
function newDeck(){deck=dances.filter(g=>g.main.he!=='ללא כותרת'&&(!roomFilter||g.records.some(v=>v.style===roomFilter)));for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}position=0}
function startDiscover(){newDeck();room.showModal();document.body.style.overflow='hidden';showDiscovery();room.querySelector('.room-close').focus()}
function nextDiscovery(){if(position<deck.length-1){position++;showDiscovery()}else{newDeck();showDiscovery()}}
function showDiscovery(){room.replaceChildren();const g=deck[position];const top=element('div','room-top');const mast=element('div');mast.append(element('span','eyebrow','DANCE NISSIM / '+t('לגלות','DISCOVER')),element('p','',t('אוסף של חיים. ריקוד אחד עכשיו.','A lifetime of dance. One moment now.')));const close=element('button','room-close',t('חזרה לספרייה ×','Back to library ×'));close.onclick=()=>room.close();top.append(mast,close);room.append(top);if(!g){room.append(element('p','',t('אין ריקודים בסינון הזה','No dances in this selection')));return}
activeRecording=g.records.find(v=>(!roomFilter||v.style===roomFilter)&&v.type==='dance')||g.main;recent=[g.key,...recent.filter(k=>k!==g.key)].slice(0,40);write('recent',recent);
const stage=element('div','room-stage'),screen=element('div','room-screen');const cover=element('button','room-cover');cover.setAttribute('aria-label',t('נגינת הריקוד: ','Play dance: ')+title(g));const playIcon=element('span','room-play');playIcon.append(icon('play'));cover.append(image(activeRecording),playIcon,element('span','room-play-label',t('נגינת הריקוד','Play this dance')));screen.append(cover);const play=v=>{activeRecording=v;const iframe=element('iframe');iframe.src=`https://www.youtube-nocookie.com/embed/${encodeURIComponent(v.id)}?autoplay=1&rel=0`;iframe.title=title(g)+' · '+kind(v);iframe.allow='autoplay; fullscreen; encrypted-media; picture-in-picture';iframe.allowFullscreen=true;screen.replaceChildren(iframe);external.href=`https://www.youtube.com/watch?v=${encodeURIComponent(v.id)}`};cover.onclick=()=>play(activeRecording);
const info=element('div','room-info');info.append(element('p','eyebrow',String(position+1).padStart(2,'0')+' / '+t('מפגש עם האוסף','FROM THE COLLECTION')),element('h2','',title(g)),element('p','room-meta',[name(activeRecording),shape(activeRecording),activeRecording.year||''].filter(Boolean).join(' · ')));
const actions=element('div','room-actions');actions.append(favorite(g));const teaching=g.records.find(v=>v.type==='teaching');if(teaching){const learn=element('button','',t('ללמוד את הצעדים','Learn the steps'));learn.onclick=()=>{play(teaching);learn.setAttribute('aria-pressed','true')};actions.append(learn)}const external=element('a','external',t('פתיחה ביוטיוב ↗','Open on YouTube ↗'));external.href=`https://www.youtube.com/watch?v=${encodeURIComponent(activeRecording.id)}`;external.target='_blank';external.rel='noopener';info.append(actions,external);stage.append(screen,info);room.append(stage);
const foot=element('div','room-bottom'),previous=element('button','',t('הריקוד הקודם','Previous dance'));previous.disabled=position===0;previous.onclick=()=>{position--;showDiscovery()};const next=element('button','primary',t('הריקוד הבא ←','Next dance →'));next.onclick=nextDiscovery;const select=element('select');select.setAttribute('aria-label',t('בחירת סוג ריקוד','Choose formation'));[['',t('כל הריקודים','All dances')],['m',t('מעגלים','Circles')],['c',t('זוגות','Couples')],['s',t('שורות','Lines')]].forEach(([value,label])=>{const o=element('option','',label);o.value=value;select.append(o)});select.value=roomFilter;select.onchange=()=>{roomFilter=select.value;newDeck();showDiscovery()};const auto=element('button','',t('ניגון אוטומטי','Autoplay next selection'));auto.setAttribute('aria-pressed',autoPlay);auto.onclick=()=>{autoPlay=!autoPlay;write('autoplay',autoPlay);auto.setAttribute('aria-pressed',autoPlay)};foot.append(previous,select,auto,next);room.append(foot,element('p','swipe-hint',t('החליקו שמאלה באזור הכותרת לריקוד הבא · מקשי החצים גם עובדים','Swipe left on the title area for the next dance · Arrow keys work too')));info.style.touchAction='pan-y';info.onpointerdown=e=>{touchStart={x:e.clientX,y:e.clientY}};info.onpointerup=e=>{if(touchStart&&touchStart.x-e.clientX>65&&Math.abs(touchStart.y-e.clientY)<65)nextDiscovery();touchStart=null};info.onpointercancel=()=>touchStart=null;syncFavorites();if(autoPlay)play(activeRecording)}
room.addEventListener('keydown',e=>{if(['SELECT','INPUT','BUTTON'].includes(e.target.tagName)&&e.target.tagName==='SELECT')return;if(e.key==='ArrowLeft'){e.preventDefault();nextDiscovery()}if(e.key==='ArrowRight'&&position>0){e.preventDefault();position--;showDiscovery()}});
room.addEventListener('close',()=>{room.replaceChildren();document.body.style.overflow='';render()});syncEntry();
